# Generated by Django 5.0.4 on 2024-05-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='original_shapes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
