# Generated by Django 5.0.4 on 2024-07-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_block_original_shapes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='encrypted_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
