# Generated by Django 5.0.6 on 2024-07-07 21:19

import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_block_encrypted_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='encrypted_data',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
