# Generated by Django 5.0.6 on 2024-07-21 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_block_encrypted_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='original_shapes',
        ),
    ]
