# Generated by Django 5.1.4 on 2025-01-19 06:18

import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_block_original_shapes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='data',
            new_name='column_hash',
        ),
        migrations.RenameField(
            model_name='block',
            old_name='encrypted_data',
            new_name='encrypted_Cb',
        ),
        migrations.AddField(
            model_name='block',
            name='encrypted_Cr',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='encrypted_Y',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
